version: '3.8'

services:
  # Local development postgres instance with postgis extension
  hydrometry:
    image: postgis/postgis:16-3.4
    ports:
      - 5433:5433
    expose:
      - "5433"
    networks:
      - hydrometry-network
    restart: always
    user: postgres
    command: -p 5433
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  pgdata:

networks:
  hydrometry-network:
    name: hydrometry-network
    driver: bridge