version: '3.8'

services:
  # Local development postgres instance with postgis extension
  postgres:
    image: postgis/postgis:16-3.4
    ports:
      - 5433:5432
    restart: always
    user: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  pgdata:
