/*
 * Dmp.Hydro.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dk.miljoeportal.vandah.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Date;
/**
 * DmpHydroApiResponsesSuccessfulResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-18T14:15:50.310248991+02:00[Europe/Copenhagen]")

public class DmpHydroApiResponsesSuccessfulResponse {
  @JsonProperty("timestamp")
  private Date timestamp = null;

  @JsonProperty("action")
  private String action = null;

  public DmpHydroApiResponsesSuccessfulResponse timestamp(Date timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Measurement datetime
   * @return timestamp
  **/
  @Schema(description = "Measurement datetime")
  public Date getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(Date timestamp) {
    this.timestamp = timestamp;
  }

  public DmpHydroApiResponsesSuccessfulResponse action(String action) {
    this.action = action;
    return this;
  }

   /**
   * Action is either &#x27;committed&#x27; or &#x27;ignored&#x27;. &#x27;committed&#x27; if written to database, &#x27;ignored&#x27; is result already existed at the given measurementDatetime (Independent of result value)
   * @return action
  **/
  @Schema(description = "Action is either 'committed' or 'ignored'. 'committed' if written to database, 'ignored' is result already existed at the given measurementDatetime (Independent of result value)")
  public String getAction() {
    return action;
  }

  public void setAction(String action) {
    this.action = action;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DmpHydroApiResponsesSuccessfulResponse dmpHydroApiResponsesSuccessfulResponse = (DmpHydroApiResponsesSuccessfulResponse) o;
    return Objects.equals(this.timestamp, dmpHydroApiResponsesSuccessfulResponse.timestamp) &&
        Objects.equals(this.action, dmpHydroApiResponsesSuccessfulResponse.action);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timestamp, action);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DmpHydroApiResponsesSuccessfulResponse {\n");
    
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
