/*
 * Dmp.Hydro.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dk.miljoeportal.vandah.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Date;
import java.time.OffsetDateTime;
/**
 * DmpHydroApiResponsesLoggerAssociationResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-27T10:11:34.799092956+02:00[Europe/Copenhagen]")

public class DmpHydroApiResponsesLoggerAssociationResponse {
  @JsonProperty("stationId")
  private String stationId = null;

  @JsonProperty("operatorStationId")
  private String operatorStationId = null;

  @JsonProperty("stationOwnerCvr")
  private String stationOwnerCvr = null;

  @JsonProperty("loggerId")
  private String loggerId = null;

  @JsonProperty("created")
  private OffsetDateTime created = null;

  @JsonProperty("effective")
  private OffsetDateTime effective = null;

  public DmpHydroApiResponsesLoggerAssociationResponse stationId(String stationId) {
    this.stationId = stationId;
    return this;
  }

   /**
   * A 8-digit station id
   * @return stationId
  **/
  @Schema(description = "A 8-digit station id")
  public String getStationId() {
    return stationId;
  }

  public void setStationId(String stationId) {
    this.stationId = stationId;
  }

  public DmpHydroApiResponsesLoggerAssociationResponse operatorStationId(String operatorStationId) {
    this.operatorStationId = operatorStationId;
    return this;
  }

   /**
   * Operator station id
   * @return operatorStationId
  **/
  @Schema(description = "Operator station id")
  public String getOperatorStationId() {
    return operatorStationId;
  }

  public void setOperatorStationId(String operatorStationId) {
    this.operatorStationId = operatorStationId;
  }

  public DmpHydroApiResponsesLoggerAssociationResponse stationOwnerCvr(String stationOwnerCvr) {
    this.stationOwnerCvr = stationOwnerCvr;
    return this;
  }

   /**
   * Station owner CVR
   * @return stationOwnerCvr
  **/
  @Schema(description = "Station owner CVR")
  public String getStationOwnerCvr() {
    return stationOwnerCvr;
  }

  public void setStationOwnerCvr(String stationOwnerCvr) {
    this.stationOwnerCvr = stationOwnerCvr;
  }

  public DmpHydroApiResponsesLoggerAssociationResponse loggerId(String loggerId) {
    this.loggerId = loggerId;
    return this;
  }

   /**
   * Logger id
   * @return loggerId
  **/
  @Schema(description = "Logger id")
  public String getLoggerId() {
    return loggerId;
  }

  public void setLoggerId(String loggerId) {
    this.loggerId = loggerId;
  }

  public DmpHydroApiResponsesLoggerAssociationResponse created(OffsetDateTime created) {
    this.created = created;
    return this;
  }

   /**
   * Date and time when the logger association was created. Blank if no logger associated
   * @return created
  **/
  @Schema(description = "Date and time when the logger association was created. Blank if no logger associated")
  public OffsetDateTime getCreated() {
    return created;
  }

  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }

  public DmpHydroApiResponsesLoggerAssociationResponse effective(OffsetDateTime effective) {
    this.effective = effective;
    return this;
  }

   /**
   * Date and time from when measurements are being read from the associated logger. Blank if no logger associated
   * @return effective
  **/
  @Schema(description = "Date and time from when measurements are being read from the associated logger. Blank if no logger associated")
  public OffsetDateTime getEffective() {
    return effective;
  }

  public void setEffective(OffsetDateTime effective) {
    this.effective = effective;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DmpHydroApiResponsesLoggerAssociationResponse dmpHydroApiResponsesLoggerAssociationResponse = (DmpHydroApiResponsesLoggerAssociationResponse) o;
    return Objects.equals(this.stationId, dmpHydroApiResponsesLoggerAssociationResponse.stationId) &&
        Objects.equals(this.operatorStationId, dmpHydroApiResponsesLoggerAssociationResponse.operatorStationId) &&
        Objects.equals(this.stationOwnerCvr, dmpHydroApiResponsesLoggerAssociationResponse.stationOwnerCvr) &&
        Objects.equals(this.loggerId, dmpHydroApiResponsesLoggerAssociationResponse.loggerId) &&
        Objects.equals(this.created, dmpHydroApiResponsesLoggerAssociationResponse.created) &&
        Objects.equals(this.effective, dmpHydroApiResponsesLoggerAssociationResponse.effective);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stationId, operatorStationId, stationOwnerCvr, loggerId, created, effective);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DmpHydroApiResponsesLoggerAssociationResponse {\n");
    
    sb.append("    stationId: ").append(toIndentedString(stationId)).append("\n");
    sb.append("    operatorStationId: ").append(toIndentedString(operatorStationId)).append("\n");
    sb.append("    stationOwnerCvr: ").append(toIndentedString(stationOwnerCvr)).append("\n");
    sb.append("    loggerId: ").append(toIndentedString(loggerId)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    effective: ").append(toIndentedString(effective)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
