/*
 * Dmp.Hydro.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dk.miljoeportal.vandah.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import dk.miljoeportal.vandah.model.DmpHydroApiRequestsLocation;
import dk.miljoeportal.vandah.model.DmpHydroApiRequestsStationIdentifier;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * DmpHydroApiRequestsUpdateStationRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-27T10:11:34.799092956+02:00[Europe/Copenhagen]")

public class DmpHydroApiRequestsUpdateStationRequest {
  @JsonProperty("station")
  private DmpHydroApiRequestsStationIdentifier station = null;

  @JsonProperty("stationOwnerCvr")
  private String stationOwnerCvr = null;

  @JsonProperty("operatorCvr")
  private String operatorCvr = null;

  @JsonProperty("operatorStationId")
  private String operatorStationId = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("location")
  private DmpHydroApiRequestsLocation location = null;

  public DmpHydroApiRequestsUpdateStationRequest station(DmpHydroApiRequestsStationIdentifier station) {
    this.station = station;
    return this;
  }

   /**
   * Get station
   * @return station
  **/
  @Schema(required = true, description = "")
  public DmpHydroApiRequestsStationIdentifier getStation() {
    return station;
  }

  public void setStation(DmpHydroApiRequestsStationIdentifier station) {
    this.station = station;
  }

  public DmpHydroApiRequestsUpdateStationRequest stationOwnerCvr(String stationOwnerCvr) {
    this.stationOwnerCvr = stationOwnerCvr;
    return this;
  }

   /**
   * Station owner cvr. Update the new station owner if it is provided
   * @return stationOwnerCvr
  **/
  @Schema(description = "Station owner cvr. Update the new station owner if it is provided")
  public String getStationOwnerCvr() {
    return stationOwnerCvr;
  }

  public void setStationOwnerCvr(String stationOwnerCvr) {
    this.stationOwnerCvr = stationOwnerCvr;
  }

  public DmpHydroApiRequestsUpdateStationRequest operatorCvr(String operatorCvr) {
    this.operatorCvr = operatorCvr;
    return this;
  }

   /**
   * Operator cvr. Update the new operator if it is provided
   * @return operatorCvr
  **/
  @Schema(description = "Operator cvr. Update the new operator if it is provided")
  public String getOperatorCvr() {
    return operatorCvr;
  }

  public void setOperatorCvr(String operatorCvr) {
    this.operatorCvr = operatorCvr;
  }

  public DmpHydroApiRequestsUpdateStationRequest operatorStationId(String operatorStationId) {
    this.operatorStationId = operatorStationId;
    return this;
  }

   /**
   * A unique operator station id within the operator organization
   * @return operatorStationId
  **/
  @Schema(description = "A unique operator station id within the operator organization")
  public String getOperatorStationId() {
    return operatorStationId;
  }

  public void setOperatorStationId(String operatorStationId) {
    this.operatorStationId = operatorStationId;
  }

  public DmpHydroApiRequestsUpdateStationRequest name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Station name
   * @return name
  **/
  @Schema(description = "Station name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public DmpHydroApiRequestsUpdateStationRequest description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Station description
   * @return description
  **/
  @Schema(description = "Station description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public DmpHydroApiRequestsUpdateStationRequest location(DmpHydroApiRequestsLocation location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @Schema(required = true, description = "")
  public DmpHydroApiRequestsLocation getLocation() {
    return location;
  }

  public void setLocation(DmpHydroApiRequestsLocation location) {
    this.location = location;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DmpHydroApiRequestsUpdateStationRequest dmpHydroApiRequestsUpdateStationRequest = (DmpHydroApiRequestsUpdateStationRequest) o;
    return Objects.equals(this.station, dmpHydroApiRequestsUpdateStationRequest.station) &&
        Objects.equals(this.stationOwnerCvr, dmpHydroApiRequestsUpdateStationRequest.stationOwnerCvr) &&
        Objects.equals(this.operatorCvr, dmpHydroApiRequestsUpdateStationRequest.operatorCvr) &&
        Objects.equals(this.operatorStationId, dmpHydroApiRequestsUpdateStationRequest.operatorStationId) &&
        Objects.equals(this.name, dmpHydroApiRequestsUpdateStationRequest.name) &&
        Objects.equals(this.description, dmpHydroApiRequestsUpdateStationRequest.description) &&
        Objects.equals(this.location, dmpHydroApiRequestsUpdateStationRequest.location);
  }

  @Override
  public int hashCode() {
    return Objects.hash(station, stationOwnerCvr, operatorCvr, operatorStationId, name, description, location);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DmpHydroApiRequestsUpdateStationRequest {\n");
    
    sb.append("    station: ").append(toIndentedString(station)).append("\n");
    sb.append("    stationOwnerCvr: ").append(toIndentedString(stationOwnerCvr)).append("\n");
    sb.append("    operatorCvr: ").append(toIndentedString(operatorCvr)).append("\n");
    sb.append("    operatorStationId: ").append(toIndentedString(operatorStationId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
