/*
 * Dmp.Hydro.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dk.miljoeportal.vandah.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import dk.miljoeportal.vandah.model.DmpHydroApiRequestsLocation;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * DmpHydroApiRequestsCreateStationRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-09-27T10:11:34.799092956+02:00[Europe/Copenhagen]")

public class DmpHydroApiRequestsCreateStationRequest {
  @JsonProperty("operatorStationId")
  private String operatorStationId = null;

  @JsonProperty("locationTypeSc")
  private Integer locationTypeSc = null;

  @JsonProperty("stationOwnerCvr")
  private String stationOwnerCvr = null;

  @JsonProperty("operatorCvr")
  private String operatorCvr = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("location")
  private DmpHydroApiRequestsLocation location = null;

  @JsonProperty("waterAreaNr")
  private String waterAreaNr = null;

  @JsonProperty("dguNumber")
  private String dguNumber = null;

  @JsonProperty("measurementPointTypeSc")
  private Integer measurementPointTypeSc = null;

  public DmpHydroApiRequestsCreateStationRequest operatorStationId(String operatorStationId) {
    this.operatorStationId = operatorStationId;
    return this;
  }

   /**
   * A unique operator station id within the operator organization
   * @return operatorStationId
  **/
  @Schema(description = "A unique operator station id within the operator organization")
  public String getOperatorStationId() {
    return operatorStationId;
  }

  public void setOperatorStationId(String operatorStationId) {
    this.operatorStationId = operatorStationId;
  }

  public DmpHydroApiRequestsCreateStationRequest locationTypeSc(Integer locationTypeSc) {
    this.locationTypeSc = locationTypeSc;
    return this;
  }

   /**
   * A subset of stancode list 1002
   * @return locationTypeSc
  **/
  @Schema(required = true, description = "A subset of stancode list 1002")
  public Integer getLocationTypeSc() {
    return locationTypeSc;
  }

  public void setLocationTypeSc(Integer locationTypeSc) {
    this.locationTypeSc = locationTypeSc;
  }

  public DmpHydroApiRequestsCreateStationRequest stationOwnerCvr(String stationOwnerCvr) {
    this.stationOwnerCvr = stationOwnerCvr;
    return this;
  }

   /**
   * Station owner CVR with the format of DK12345678
   * @return stationOwnerCvr
  **/
  @Schema(required = true, description = "Station owner CVR with the format of DK12345678")
  public String getStationOwnerCvr() {
    return stationOwnerCvr;
  }

  public void setStationOwnerCvr(String stationOwnerCvr) {
    this.stationOwnerCvr = stationOwnerCvr;
  }

  public DmpHydroApiRequestsCreateStationRequest operatorCvr(String operatorCvr) {
    this.operatorCvr = operatorCvr;
    return this;
  }

   /**
   * Operator CVR with the format of DK12345678
   * @return operatorCvr
  **/
  @Schema(description = "Operator CVR with the format of DK12345678")
  public String getOperatorCvr() {
    return operatorCvr;
  }

  public void setOperatorCvr(String operatorCvr) {
    this.operatorCvr = operatorCvr;
  }

  public DmpHydroApiRequestsCreateStationRequest name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Station name
   * @return name
  **/
  @Schema(description = "Station name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public DmpHydroApiRequestsCreateStationRequest description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Station description
   * @return description
  **/
  @Schema(description = "Station description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public DmpHydroApiRequestsCreateStationRequest location(DmpHydroApiRequestsLocation location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @Schema(required = true, description = "")
  public DmpHydroApiRequestsLocation getLocation() {
    return location;
  }

  public void setLocation(DmpHydroApiRequestsLocation location) {
    this.location = location;
  }

  public DmpHydroApiRequestsCreateStationRequest waterAreaNr(String waterAreaNr) {
    this.waterAreaNr = waterAreaNr;
    return this;
  }

   /**
   * Water area number
   * @return waterAreaNr
  **/
  @Schema(description = "Water area number")
  public String getWaterAreaNr() {
    return waterAreaNr;
  }

  public void setWaterAreaNr(String waterAreaNr) {
    this.waterAreaNr = waterAreaNr;
  }

  public DmpHydroApiRequestsCreateStationRequest dguNumber(String dguNumber) {
    this.dguNumber = dguNumber;
    return this;
  }

   /**
   * DGU number of Groundwater station
   * @return dguNumber
  **/
  @Schema(description = "DGU number of Groundwater station")
  public String getDguNumber() {
    return dguNumber;
  }

  public void setDguNumber(String dguNumber) {
    this.dguNumber = dguNumber;
  }

  public DmpHydroApiRequestsCreateStationRequest measurementPointTypeSc(Integer measurementPointTypeSc) {
    this.measurementPointTypeSc = measurementPointTypeSc;
    return this;
  }

   /**
   * The stancode of measurement point type (subset of stancode list 1002) that is created with the station automatically. If it is not presented, measurement point type is decided by the system
   * @return measurementPointTypeSc
  **/
  @Schema(description = "The stancode of measurement point type (subset of stancode list 1002) that is created with the station automatically. If it is not presented, measurement point type is decided by the system")
  public Integer getMeasurementPointTypeSc() {
    return measurementPointTypeSc;
  }

  public void setMeasurementPointTypeSc(Integer measurementPointTypeSc) {
    this.measurementPointTypeSc = measurementPointTypeSc;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DmpHydroApiRequestsCreateStationRequest dmpHydroApiRequestsCreateStationRequest = (DmpHydroApiRequestsCreateStationRequest) o;
    return Objects.equals(this.operatorStationId, dmpHydroApiRequestsCreateStationRequest.operatorStationId) &&
        Objects.equals(this.locationTypeSc, dmpHydroApiRequestsCreateStationRequest.locationTypeSc) &&
        Objects.equals(this.stationOwnerCvr, dmpHydroApiRequestsCreateStationRequest.stationOwnerCvr) &&
        Objects.equals(this.operatorCvr, dmpHydroApiRequestsCreateStationRequest.operatorCvr) &&
        Objects.equals(this.name, dmpHydroApiRequestsCreateStationRequest.name) &&
        Objects.equals(this.description, dmpHydroApiRequestsCreateStationRequest.description) &&
        Objects.equals(this.location, dmpHydroApiRequestsCreateStationRequest.location) &&
        Objects.equals(this.waterAreaNr, dmpHydroApiRequestsCreateStationRequest.waterAreaNr) &&
        Objects.equals(this.dguNumber, dmpHydroApiRequestsCreateStationRequest.dguNumber) &&
        Objects.equals(this.measurementPointTypeSc, dmpHydroApiRequestsCreateStationRequest.measurementPointTypeSc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operatorStationId, locationTypeSc, stationOwnerCvr, operatorCvr, name, description, location, waterAreaNr, dguNumber, measurementPointTypeSc);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DmpHydroApiRequestsCreateStationRequest {\n");
    
    sb.append("    operatorStationId: ").append(toIndentedString(operatorStationId)).append("\n");
    sb.append("    locationTypeSc: ").append(toIndentedString(locationTypeSc)).append("\n");
    sb.append("    stationOwnerCvr: ").append(toIndentedString(stationOwnerCvr)).append("\n");
    sb.append("    operatorCvr: ").append(toIndentedString(operatorCvr)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    waterAreaNr: ").append(toIndentedString(waterAreaNr)).append("\n");
    sb.append("    dguNumber: ").append(toIndentedString(dguNumber)).append("\n");
    sb.append("    measurementPointTypeSc: ").append(toIndentedString(measurementPointTypeSc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
