services:
    ingestion:
        container_name: "vanda_hydrometry_data_ingestion"
        build:
            context: ../.
            dockerfile: docker/Dockerfile_dev
        environment:
            - "TZ=Europe/Copenhagen"
            - SPRING_DATASOURCE_URL=jdbc:postgresql://dbprimo.cuddlefish.intern:11186/vanda_hydrometry_test?user=vanda_hydrometry_test&password=26THroobbing67swingiNgArOmaa10?Tuumble
        networks:
            - "default"
        volumes:
            - ../log/vandah.log:/log/vandah.log
        command:
          - "waterlevels"
          - "--stationId=all"
          - "--saveDb"

networks:
  default:
    name: "vanda_hydrometry_data_ingestion_network"