services:
    ingestion:
        container_name: "vanda_hydrometry_data_ingestion"
        build:
            context: ../.
            dockerfile: docker/Dockerfile_dev
        environment:
            - "TZ=Europe/Copenhagen"
        networks:
            - "default"
        volumes:
            - ../log/vandah.log:/log/vandah.log
        command:
          - "stations"
          - "--examinationTypeSc=25"
          - "--saveDb"

networks:
  default:
    name: "vanda_hydrometry_data_ingestion_network"