services:
    ingestion:
        container_name: "vanda_hydrometry_data_ingestion"
        build:
            context: ../.
            dockerfile: docker/Dockerfile_dev
        environment:
            - "TZ=Europe/Copenhagen"
        networks:
            - "default"
        volumes:
          - ../log/vandah.log:/log/vandah.log
        command:
          - "streamdischarge"
          - "--stationId=all"
          - "--from=1900-01-01T00:00Z"
          - "--to=2024-12-13T11:24Z"
          - "--saveDb"

networks:
  default:
    name: "vanda_hydrometry_data_ingestion_network"